"""
Test script for EmbeddedResource handling in MCP tool results.

This tests the new resource handling added to process_tool_result()
to ensure it properly processes MCP EmbeddedResource content types.
"""

import json
import base64


# Mock test data representing different MCP CallToolResult scenarios

def create_test_image_resource():
    """Simulate an MCP tool returning an image via EmbeddedResource"""
    # Create a small 1x1 red pixel PNG
    red_pixel_png = base64.b64encode(
        b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x00\x01\x00\x00\x00\x01'
        b'\x08\x02\x00\x00\x00\x90wS\xde\x00\x00\x00\x0cIDATx\x9cc\xf8\xcf'
        b'\xc0\x00\x00\x00\x03\x00\x01\x00\x18\xdd\x8d\xb4\x00\x00\x00\x00IEND\xaeB`\x82'
    ).decode('utf-8')

    return {
        "type": "resource",
        "resource": {
            "uri": "generated/image-001.png",
            "mimeType": "image/png",
            "blob": red_pixel_png
        }
    }


def create_test_text_resource():
    """Simulate an MCP tool returning a text file via EmbeddedResource"""
    return {
        "type": "resource",
        "resource": {
            "uri": "output/report.txt",
            "mimeType": "text/plain",
            "text": "This is a test report generated by the MCP tool.\nIt contains multiple lines."
        }
    }


def create_test_html_resource():
    """Simulate an MCP tool returning HTML content via EmbeddedResource"""
    return {
        "type": "resource",
        "resource": {
            "uri": "visualization.html",
            "mimeType": "text/html",
            "text": "<div style='background: blue; color: white; padding: 20px;'>Interactive Visualization</div>"
        }
    }


def create_test_mixed_content():
    """Simulate an MCP tool returning multiple content types"""
    return [
        {
            "type": "text",
            "text": "Generated 2 variations:"
        },
        create_test_image_resource(),
        {
            "type": "resource",
            "resource": {
                "uri": "generated/image-002.png",
                "mimeType": "image/png",
                "blob": base64.b64encode(b"fake-image-data-2").decode('utf-8')
            }
        },
        {
            "type": "text",
            "text": "Processing complete!"
        }
    ]


def create_test_audio_resource():
    """Simulate an MCP tool returning audio via EmbeddedResource"""
    return {
        "type": "resource",
        "resource": {
            "uri": "output/speech.mp3",
            "mimeType": "audio/mpeg",
            "blob": base64.b64encode(b"fake-audio-data").decode('utf-8')
        }
    }


def create_test_pdf_resource():
    """Simulate an MCP tool returning a PDF via EmbeddedResource"""
    return {
        "type": "resource",
        "resource": {
            "uri": "report.pdf",
            "mimeType": "application/pdf",
            "blob": base64.b64encode(b"%PDF-1.4 fake pdf content").decode('utf-8')
        }
    }


# Test scenarios
test_scenarios = {
    "image_resource": {
        "name": "Image Generation via EmbeddedResource",
        "tool_result": [create_test_image_resource()],
        "expected_files_count": 1,
        "expected_file_type": "image"
    },
    "text_resource": {
        "name": "Text File via EmbeddedResource",
        "tool_result": [create_test_text_resource()],
        "expected_files_count": 0,  # Text resources go to tool_response
        "expected_response_type": "dict"
    },
    "html_resource": {
        "name": "HTML Content via EmbeddedResource",
        "tool_result": [create_test_html_resource()],
        "expected_embeds_count": 1,
        "expected_files_count": 0
    },
    "mixed_content": {
        "name": "Mixed Content Types",
        "tool_result": create_test_mixed_content(),
        "expected_files_count": 2,  # Two images
        "expected_response_contains": "Generated 2 variations"
    },
    "audio_resource": {
        "name": "Audio via EmbeddedResource",
        "tool_result": [create_test_audio_resource()],
        "expected_files_count": 1,
        "expected_file_type": "audio"
    },
    "pdf_resource": {
        "name": "PDF Document via EmbeddedResource",
        "tool_result": [create_test_pdf_resource()],
        "expected_files_count": 1,
        "expected_file_type": "pdf"
    }
}


def print_test_scenario(scenario_key, scenario):
    """Print a test scenario in a readable format"""
    print(f"\n{'='*70}")
    print(f"Test Scenario: {scenario['name']}")
    print(f"{'='*70}")
    print(f"\nInput (tool_result):")
    print(json.dumps(scenario['tool_result'], indent=2))
    print(f"\nExpected Results:")
    for key, value in scenario.items():
        if key not in ['name', 'tool_result']:
            print(f"  {key}: {value}")


def main():
    """Print all test scenarios"""
    print("MCP EmbeddedResource Test Scenarios")
    print("====================================")
    print("\nThese scenarios test the new resource handling in process_tool_result()")
    print("Each scenario represents a different MCP CallToolResult content type.\n")

    for key, scenario in test_scenarios.items():
        print_test_scenario(key, scenario)

    print(f"\n{'='*70}")
    print("Testing Instructions:")
    print("="*70)
    print("""
1. Use these test scenarios with an MCP server or mock responses
2. Verify that process_tool_result() correctly handles each type:
   - Image resources → tool_result_files with type="image"
   - Audio resources → tool_result_files with type="audio"
   - PDF resources → tool_result_files with type="pdf"
   - Text resources → tool_response with content
   - HTML resources → tool_result_embeds for iframe display
3. Check that URIs and mimeTypes are preserved
4. Verify frontend displays files correctly in message.files
5. Verify embeds render in message.embeds
""")


if __name__ == "__main__":
    main()
